# Generated by Django 2.1.7 on 2019-02-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaggageBelt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('status', models.IntegerField(blank=True, default=1, null=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('status', models.IntegerField(blank=True, default=1, null=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escalator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('message', models.CharField(blank=True, default='', max_length=120, null=True)),
                ('status', models.IntegerField(blank=True, default=1, null=True)),
                ('last_update', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
