# Generated by Django 2.0.7 on 2019-03-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bridgeTable',
            fields=[
                ('bridgeTableID', models.IntegerField(primary_key=True, serialize=False)),
                ('Bridge_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='N/A', max_length=6)),
                ('PCA_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='N/A', max_length=6)),
                ('GPU_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='N/A', max_length=6)),
            ],
            options={
                'permissions': (('has_write_access', 'Can change the status'),),
            },
        ),
        migrations.CreateModel(
            name='Elevators',
            fields=[
                ('elevatorID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Elevator_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('RED', 'Red'), ('NA', 'Not Available')], default='N/A', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Escalators',
            fields=[
                ('escalatorID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Escalator_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('RED', 'Red'), ('NA', 'Not Available')], default='N/A', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=240)),
            ],
        ),
    ]
