# Generated by Django 2.0.7 on 2019-11-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bridgeTable',
            fields=[
                ('bridgeTableID', models.IntegerField(primary_key=True, serialize=False)),
                ('Bridge_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='N/A', max_length=6)),
                ('PCA_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='N/A', max_length=6)),
                ('GPU_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='N/A', max_length=6)),
            ],
            options={
                'permissions': (('has_write_access', 'Can change the status'),),
            },
        ),
        migrations.CreateModel(
            name='domIntBaggageSystems',
            fields=[
                ('domIntBaggageID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('DomIntBaggage_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='N/A', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='domIntOversize',
            fields=[
                ('domIntOversizeID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('DomIntOversize_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='N/A', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='domIntPBS',
            fields=[
                ('domIntPBSID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('DomIntPBS_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='N/A', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='electricalCharging',
            fields=[
                ('electricalChargingID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('ElectricalCharging_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='N/A', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Elevators',
            fields=[
                ('elevatorID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('elevatorTableID', models.IntegerField(unique=True)),
                ('Elevator_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('RED', 'Red')], default='N/A', max_length=5)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Escalators',
            fields=[
                ('escalatorID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('Escalator_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('RED', 'Red')], default='N/A', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='lavHut',
            fields=[
                ('lavHutID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('LavHut_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='N/A', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('message', models.CharField(max_length=240)),
                ('messageID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='tbBaggageSystems',
            fields=[
                ('tbBaggageID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('TbBaggage_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='N/A', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='tbOversize',
            fields=[
                ('tbOversizeID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('TbOversize_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='N/A', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='tbPBS',
            fields=[
                ('tbPBSID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('TbPBS_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='N/A', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='waterFill',
            fields=[
                ('waterFillID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('WaterFill_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='N/A', max_length=6)),
            ],
        ),
    ]
