# Generated by Django 2.0.7 on 2019-03-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_board', '0002_domintbaggagesystems_domintoversize_tbbaggagesystems_tboversize'),
    ]

    operations = [
        migrations.CreateModel(
            name='domIntPBS',
            fields=[
                ('domIntPBSID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('DomIntPBS_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('NA', 'Not Available')], default='N/A', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='electricalCharging',
            fields=[
                ('electricalChargingID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('ElectricalCharging_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('NA', 'Not Available')], default='N/A', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='lavaHut',
            fields=[
                ('lavaHutID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('LavaHut_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('NA', 'Not Available')], default='N/A', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='tbPBS',
            fields=[
                ('tbPBSID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('TbPBS_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('NA', 'Not Available')], default='N/A', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='waterFill',
            fields=[
                ('waterFillID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('WaterFill_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('RED', 'Red'), ('YELLOW', 'Yellow'), ('NA', 'Not Available')], default='N/A', max_length=5)),
            ],
        ),
    ]
