# Generated by Django 2.0.7 on 2019-03-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_board', '0002_auto_20190328_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='domIntPBS',
            fields=[
                ('domIntPBSID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('DomIntPBS_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='N/A', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='electricalCharging',
            fields=[
                ('electricalChargingID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('ElectricalCharging_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='N/A', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='lavHut',
            fields=[
                ('lavHutID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('LavHut_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='N/A', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='tbPBS',
            fields=[
                ('tbPBSID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('TbPBS_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='N/A', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='waterFill',
            fields=[
                ('waterFillID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('WaterFill_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='N/A', max_length=6)),
            ],
        ),
        migrations.AlterField(
            model_name='domintbaggagesystems',
            name='DomIntBaggage_Status_Choice',
            field=models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='N/A', max_length=6),
        ),
        migrations.AlterField(
            model_name='domintoversize',
            name='DomIntOversize_Status_Choice',
            field=models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='N/A', max_length=6),
        ),
        migrations.AlterField(
            model_name='tbbaggagesystems',
            name='TbBaggage_Status_Choice',
            field=models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='N/A', max_length=6),
        ),
        migrations.AlterField(
            model_name='tboversize',
            name='TbOversize_Status_Choice',
            field=models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='N/A', max_length=6),
        ),
    ]
