# Generated by Django 2.0.7 on 2019-04-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_board', '0003_auto_20190330_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='newModel',
            fields=[
                ('newModelID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('NewModel_Status_Choice', models.CharField(choices=[('GREEN', 'Green'), ('YELLOW', 'Yellow'), ('RED', 'Red')], default='N/A', max_length=6)),
            ],
        ),
    ]
