# Generated by Django 2.0.7 on 2019-04-02 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status_board', '0004_newmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newModel',
        ),
    ]
