# Generated by Django 2.0.7 on 2019-10-17 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_board', '0005_delete_newmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevators',
            name='elevatorNum',
            field=models.IntegerField(default=' '),
        ),
    ]
