# Generated by Django 2.0.7 on 2019-10-26 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_board', '0005_delete_newmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevators',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
