# Generated by Django 2.0.7 on 2019-10-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_board', '0006_elevators_elevatornum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevators',
            name='elevatorNum',
            field=models.IntegerField(default='-1'),
        ),
    ]
