# Generated by Django 2.0.7 on 2019-10-26 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_board', '0006_elevators_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevators',
            name='elevatorTableID',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
