# Generated by Django 2.0.7 on 2019-10-26 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_board', '0007_elevators_elevatortableid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevators',
            name='elevatorTableID',
            field=models.IntegerField(unique=True),
        ),
    ]
