# Generated by Django 2.0.7 on 2019-10-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('status_board', '0007_auto_20191016_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevators',
            name='elevatorNum',
            field=models.IntegerField(default='0s'),
        ),
    ]
