# Generated by Django 2.0.7 on 2019-10-17 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status_board', '0011_auto_20191016_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevators',
            name='elevatorNum',
        ),
    ]
